### ISSUE TITLE
echo-sd の npm のラッパーを作りました

### ISSUE THREAD

**Issue by kamataryo** [fumiyas/home-commands#2]
こんにちは。 echo-sd をいつも楽しく使っています。issue ではないのですがここに書かせていただきます。

echo-sd の npm 版のラッパーを作りました。

https://www.npmjs.com/package/echo-sd
https://github.com/kamataryo/node-echo-sd

Node.js (v8以降) のユーザーでしたら、 echo-sd の事前のインストール不要で、以下のコマンドで echo-sd が即時に使えるようになりました。

```shell
$ npx echo-sd
_人人人人人人_
> 突然の死 <
￣Y^Y^Y^Y^Y^Y￣
```

もしお気に障る点がありましたら公開停止したいと思いますので、お手数ですがご指摘いただけると助かります。

**Comment by fumiyas** [comment]
Node.js まったくわからないので、どんな仕掛けかどれだけ便利(?)なのかまったくわからないですが、まったく問題ないですよ。ありがとうございます!

**Comment by kamataryo** [comment]
ありがとうございます！
